# Generated by Django 4.0 on 2021-12-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Owned_games', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_name', models.CharField(max_length=300)),
                ('Owner', models.CharField(max_length=30)),
                ('Game_description', models.TextField()),
                ('Latest_borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game_groups.gamer')),
            ],
        ),
    ]
