# Generated by Django 4.0 on 2021-12-11 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borrow_date', models.DateTimeField(auto_now_add=True)),
                ('Planned_return_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='Latest_borrower',
        ),
        migrations.AddField(
            model_name='game',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='is_borrowed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gamer',
        ),
        migrations.AddField(
            model_name='borrow',
            name='Borrowed_Game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game_groups.game'),
        ),
    ]
