# Generated by Django 4.0 on 2021-12-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_groups', '0002_borrow_remove_game_latest_borrower_game_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='Contact_information',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
