# Generated by Django 4.0 on 2021-12-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_groups', '0004_rename_borrow_date_borrow_borrow_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_borrowed',
        ),
        migrations.AddField(
            model_name='borrow',
            name='is_borrowed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
