# Generated by Django 4.0 on 2021-12-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_groups', '0006_alter_borrow_is_borrowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='is_borrowed',
        ),
        migrations.AddField(
            model_name='game',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
