# Generated by Django 4.0 on 2021-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_groups', '0009_remove_borrow_contact_information_borrow_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='planned_return_date',
            field=models.DateTimeField(),
        ),
    ]
