# Generated by Django 4.0 on 2021-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_groups', '0011_alter_borrow_planned_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='planned_return_date',
            field=models.CharField(max_length=20),
        ),
    ]
