# Generated by Django 4.0 on 2021-12-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_groups', '0012_alter_borrow_planned_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
