# Generated by Django 4.0 on 2021-12-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_groups', '0013_borrow_is_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='planned_return_date',
            field=models.DateTimeField(),
        ),
    ]
